RELATION_VERBS = {
    'isRepresentedBy', 'nominates', 'isBasedOn', 'partOf', 'cause', 'imply',
    'LegalRequirement', 'Marketing', 'publicPowers', 'Purpose',
    'PartyOf', 'ViolationOf', 'codeOfConduct',
    'ApprovedCertificationMechanism', 'StandardContractualClause',
    'confidentialWrt',
}

CONTEXT_PREDICATES = {
    'PersonalData', 'PersonalDataProcessing', 'DataSubject', 'Controller',
    'Processor', 'SupervisoryAuthority', 'MemberState',
    'nominates', 'isBasedOn', 'Purpose', 'partOf', 'isRepresentedBy',
    'ResponsibleFor', 'LegalRequirement', 'publicPowers', 'Marketing',
    'Contract', 'PartyOf', 'ViolationOf', 'StandardContractualClause',
    'AdhereTo', 'codeOfConduct', 'ApprovedCertificationMechanism',
    'RelatedTo', 'WorkIn', 'AssistFor', 'AuthorizedBy',
    'confidentialWrt', 'Return', 'Define',
    'Communicate', 'Transmit', 'Execute', 'Request', 'Hold', 'cause',
    'imply', 'PublicInterest',
}

HUMANIZER = {
    "Communicate'": "Notify",
    "Communicate": "Notify",
    "LetterReasonFor": "Provide Reason for Delay",
    "Document'": "Document",
    "Document": "Document",
    "ComplyWith": "Comply With Obligations",
    "Verify": "Verify",
    "Provide": "Provide Information",
    "DataBreach": "Data Breach Detected",
    "AwareOf": "Became Aware of Breach",
    "AwareOf'": "Became Aware of Breach",
    "PersonalDataProcessing": "Personal Data Processing",
    "PersonalDataProcessing'": "Personal Data Processing",
    "Process": "Process Personal Data",
    "Measure": "Measures Taken/Proposed",
    "TakenToAddress": "Measures Already Taken",
    "ProposedToAddress": "Measures Proposed",
    "natureOf": "Nature of Breach",
    "dpoOrCP": "Provide Contact Details",
    "dpoOrCp": "Provide Contact Details",
    "imply": "Likely Consequences",
    "contactDetails": "Contact Details",
    "Risk": "High Risk to Individuals",
    "likely": "Likely to Result in Risk",
    "riskinessRightsFreedoms": "Risk to Rights and Freedoms",
    "feasible": "Feasible",
    "nominates": "Processor Nominates Controller",
    "allInfoAbout": "All Info About the Breach",
    "SupervisoryAuthority": "Supervisory Authority",
    "Delete": "Erase Personal Data",
    "Rectify": "Rectify Data",
    "Access": "Provide Data Access",
    "Lodge": "Lodge Complaint",
    "ReceiveFrom": "Receive Communication",
    "Charge": "Charge Fee",
    "WithdrawConsent": "Withdraw Consent",
    "Register": "Maintain Processing Record",
    "WriteIn": "Record Processing Activity",
    "Implement": "Implement Measure",
    "ResponsibleFor": "Bear Legal Responsibility",
    "CompensationFor": "Receive Compensation",
    "PayFor": "Pay Compensation",
    "HasBeenDamaged": "Damage Suffered",
    "Request": "Submit Request",
    "ViolationOf": "GDPR Violation",
    "Transmit": "Transmit Data",
    "Execute": "Execute Processing",
    "Hold": "Hold Data",
    "RelatedTo": "Related Processing",
    "AdhereTo": "Adhere to Rules",
    "AssistFor": "Assist With Compliance",
    "Return": "Return Personal Data",
    "WorkIn": "Work In Capacity",
    "AuthorizedBy": "Authorized By Controller",
    "Define": "Define Processing Scope",
    "Contract": "Enter Contract",
    "Demonstrate": "Demonstrate Compliance",
    "reasonable": "Use reasonable effort",
    "publicPowers": "Official Authority Task",
    "Public_Body": "Public Body Records",
    "ThirdParty": "Third-Party Recipient",
    "Marketing": "Direct Marketing",
    "TakeIntoAccount": "Take Risk Into Account",
    "clearness": "Use Clear Language",
    "machineReadableness": "Provide Machine-Readable Information",
    "PartyOf": "Enter Arrangement",
    "isRepresentedBy": "Be Represented By",
    "confidentialWrt": "Keep Confidential",
    "AdequateWith": "Ensure Adequacy",
    "designates": "Designate Data Protection Officer",
    "ExpertIn": "Have Expert Knowledge",
    "Publish": "Publish Information",
    "ConflictOfInterest": "Avoid Conflict of Interest",
    "Monitor": "Monitor Compliance",
    "CooperateWith": "Cooperate With Authority",
    "Protect": "Protect Rights and Freedoms",
    "Research": "Research Purpose",
    "Statistic": "Statistical Purpose",
    "JudicialRemedy": "Seek Judicial Remedy",
    "ThePublic": "Inform the Public",
    "ReachableFrom": "Be Easily Reachable",
    "OfferGoodsOrServices": "Offer Goods or Services",
    "JointDataController": "Joint Controllers Involved",
    "DPO": "Data Protection Officer",
    "Recipient": "Recipients",
    "CategoryOf": "Categories of Data",
    "AutomatedDecisionMaking": "Automated Decision-Making",
    "HasSignificantEffectOn": "Significant Effect",
    "LegalEffectOn": "Legal Effect",
    "BiometricData": "Biometric Data",
    "EthnicData": "Ethnic Origin Data",
    "GeneticData": "Genetic Data",
    "HealthData": "Health Data",
    "largeScale": "Large-Scale Processing",
    "publicArea": "Publicly Accessible Area",
    "Identify": "Identify the Requester",
    "AttachTo": "Attach Standard Icons",
    "AccreditedBy": "Be Accredited By",
    "Mandate": "Mandate a Representative Body",
    "ContactPointFor": "Provide Contact Point",
    "public": "Make Information Public",
    "AdviseOn": "Advise On Compliance",
    "DataProtectionPolicies": "Data Protection Policies",
    "BodyCC": "Monitoring Body",
    "copyOf": "Copy of Personal Data",
    "legalBasisOf": "Legal Basis",
    "numberOfDSConcerned": "Number of Data Subjects Concerned",
    "numberOfPDRConcerned": "Number of Data Records Concerned",
    "progressOf": "Progress Update",
    "draftOf": "Draft Notification",
    "highestManagementLevel": "Highest Management Level",
    "countryOf": "Country",
    "minAgeForConsent": "Minimum Consent Age",
    "ageOf": "Age of Data Subject",
    "ThirdCountry": "Third Country",
    "InternationalOrganization": "International Organization",
    "oralForm": "Oral Form",
    "lessThanOrEqual": "At or Below Threshold",
    "equal": "Equals",
    "Override": "Override",
    "rightsAndFreedoms": "Rights and Freedoms",
    "legitimateInterest": "Legitimate Interest",
}

COND_HUMANIZER = {
    "Risk": "High Risk to Individuals",
    "likely": "Likely to Cause Risk",
    "riskinessRightsFreedoms": "Risk to Rights & Freedoms",
    "Person": "Natural Person Affected",
    "nominates": "Processor Nominates Representative",
    "feasible": "Notification Feasible",
    "NOT Possible": "NOT all info available yet",
    "Partial Information Available": "Further details can follow later",
    "ViolationOf": "GDPR Violation",
    "DPO": "Data Protection Officer Appointed",
    "CategoryOf": "Categories of Data",
    "Recipient": "Recipients Identified",
    "JointDataController": "Joint Controllers Involved",
    "AutomatedDecisionMaking": "Automated Decision-Making",
    "HasSignificantEffectOn": "Significant Effect on the Person",
    "LegalEffectOn": "Legal Effect on the Person",
    "BiometricData": "Biometric Data",
    "EthnicData": "Ethnic Origin Data",
    "GeneticData": "Genetic Data",
    "HealthData": "Health Data",
    "largeScale": "Large-Scale Processing",
    "publicArea": "Publicly Accessible Area",
    "Research": "Research Purpose",
    "Statistic": "Statistical Purpose",
    "Judicial": "Judicial Context",
    "Protect": "Protect Rights and Freedoms",
    "DataProtectionPolicies": "Data Protection Policies",
    "OfferGoodsOrServices": "Offers Goods or Services",
    "ReachableFrom": "Easily Reachable",
    "Represent": "Representative Bodies Involved",
    "Monitor": "Monitoring Activities",
    "BodyCC": "Monitoring Body",
    "publicInterest": "Public Interest Processing",
    "lawfulness": "Processing Was Lawful",
    "Consent": "Original Consent Given",
    "GiveConsent": "Data Subject Gave Consent",
    "WithdrawConsent": "Consent Withdrawn",
    "public": "Information Made Public",
    "accurate": "Data is Accurate",
    "PersonalDataRecord": "Processing Record Exists",
    "Store": "Data Stored",
    "Marketing": "Direct Marketing",
    "publicPowers": "Official Authority Task",
    "ThirdParty": "Third-Party Recipient",
    "Public_Body": "Public Body Records",
    "Representative": "Controller Has Representative",
    "requireTooMuchEffort": "Disproportionate Effort",
    "Demonstrate": "Compliance Demonstrated",
    "Comply With Obligations": "Obligations Complied With",
    "Maintain Processing Record": "Processing Record Maintained",
    "ThirdCountry": "Transfer to Third Country",
    "InternationalOrganization": "Transfer to International Organization",
    "legitimateInterest": "Legitimate Interest",
    "rightsAndFreedoms": "Rights and Freedoms",
    "countryOf": "Country",
    "minAgeForConsent": "Minimum Consent Age",
    "ageOf": "Age of Data Subject",
}

RECIPIENT_HUMANIZER = {
    'SupervisoryAuthority': 'Supervisory Authority',
    'Controller': 'Controller',
    'Processor': 'Processor',
    'DataSubject': 'Data Subject',
}

RAW_SKIP_LABELS = {
    'Describe',
    "Describe'",
    'Contain',
    "Contain'",
    'and',
    'or',
    'System',
    'partOf',
    'Notify',
    'Document',
    'Verify',
    'Comply With Obligations',
    'Provide Reason for Delay',
    "Communicate'",
    "Communicate",
    "LetterReasonFor",
    "ComplyWith",
    "Document'",
    "Define",
}
